### ISSUE TITLE
Syntax error after updating

### ISSUE THREAD

**Issue by testt23** [luyadev/luya-module-remoteadmin#11]
![IMG_20200112_121940](https://user-images.githubusercontent.com/3694008/72217443-5d6aae00-3536-11ea-9353-6a685bb09ec8.png)

I have updated Luya kernel and luya plugins and after updating I have error:

Syntax error

Yii debug is ON

**Comment by nadar** [comment]
Please provide full stack trace from the exception, otherwise we can not help fix this. Take a look at the xhr request which throws the error

**Comment by testt23** [comment]
)]}',
{"name":"Exception","message":"Syntax error.","code":4,"type":"yii\\base\\InvalidArgumentException","file":"/home/USER/luya-kickstarter/vendor/yiisoft/yii2/helpers/BaseJson.php","line":133,"stack-trace":["#0 /home/USER/luya-kickstarter/vendor/yiisoft/yii2/helpers/BaseJson.php(107): yii\\helpers\\BaseJson::handleJsonError(4)","#1 /home/USER/luya-kickstarter/vendor/luyadev/luya-module-remoteadmin/src/models/Site.php(391): yii\\helpers\\BaseJson::decode('<!DOCTYPE html>...')","#2 [internal function]: luya\\remoteadmin\\models\\Site->luya\\remoteadmin\\models\\{closure}(Object(luya\\remoteadmin\\models\\Site))","#3 /home/USER/luya-kickstarter/vendor/luyadev/luya-core/traits/CacheableTrait.php(110): call_user_func(Object(Closure), Object(luya\\remoteadmin\\models\\Site))","#4 /home/USER/luya-kickstarter/vendor/luyadev/luya-module-remoteadmin/src/models/Site.php(405): luya\\remoteadmin\\models\\Site->getOrSetHasCache(Array, Object(Closure), 3600)","#5 /home/USER/luya-kickstarter/vendor/luyadev/luya-module-remoteadmin/src/models/Site.php(274): luya\\remoteadmin\\models\\Site->getPackageVersion(NULL)","#6 /home/USER/luya-kickstarter/vendor/yiisoft/yii2/base/Component.php(139): luya\\remoteadmin\\models\\Site->getPackages()","#7 /home/USER/luya-kickstarter/vendor/yiisoft/yii2/db/BaseActiveRecord.php(298): yii\\base\\Component->__get('packages')","#8 /home/USER/luya-kickstarter/vendor/yiisoft/yii2/base/ArrayableTrait.php(126): yii\\db\\BaseActiveRecord->__get('packages')","#9 /home/USER/luya-kickstarter/vendor/yiisoft/yii2/rest/Serializer.php(260): yii\\base\\Model->toArray(Array, Array)","#10 /home/USER/luya-kickstarter/vendor/yiisoft/yii2/rest/Serializer.php(150): yii\\rest\\Serializer->serializeModel(Object(luya\\remoteadmin\\models\\Site))","#11 /home/USER/luya-kickstarter/vendor/yiisoft/yii2/rest/Controller.php(99): yii\\rest\\Serializer->serialize(Object(luya\\remoteadmin\\models\\Site))","#12 /home/USER/luya-kickstarter/vendor/yiisoft/yii2/rest/Controller.php(77): yii\\rest\\Controller->serializeData(Object(luya\\remoteadmin\\models\\Site))","#13 /home/USER/luya-kickstarter/vendor/yiisoft/yii2/base/Controller.php(159): yii\\rest\\Controller->afterAction(Object(luya\\admin\\ngrest\\base\\actions\\ViewAction), Object(luya\\remoteadmin\\models\\Site))","#14 /home/USER/luya-kickstarter/vendor/yiisoft/yii2/base/Module.php(528): yii\\base\\Controller->runAction('view', Array)","#15 /home/USER/luya-kickstarter/vendor/yiisoft/yii2/web/Application.php(103): yii\\base\\Module->runAction('admin/api-remot...', Array)","#16 /home/USER/luya-kickstarter/vendor/luyadev/luya-core/web/Application.php(48): yii\\web\\Application->handleRequest(Object(luya\\web\\Request))","#17 /home/USER/luya-kickstarter/vendor/yiisoft/yii2/base/Application.php(386): luya\\web\\Application->handleRequest(Object(luya\\web\\Request))","#18 /home/USER/luya-kickstarter/vendor/luyadev/luya-core/base/Boot.php(268): yii\\base\\Application->run()","#19 /home/USER/luya-kickstarter/vendor/luyadev/luya-core/base/Boot.php(208): luya\\base\\Boot->applicationWeb()","#20 /home/USER/luya-kickstarter/public_html/index.php(8): luya\\base\\Boot->run()","#21 {main}"]}

**Comment by nadar** [comment]
So it seems one or more packages are unable to retrieve its packagist content, maybe we should check the response status:

https://github.com/luyadev/luya-module-remoteadmin/blob/master/src/models/Site.php#L390

**Comment by testt23** [comment]
I have debug this:


    		$curl->get('https://packagist.org/packages/'.$package.'.json');
    		//print_r($curl);
    		$json = Json::decode($curl->response);
    		//print_r($json);

**Comment by nadar** [comment]
ok thanks. But this is the response only for one package i assume? Or this is the package which throws the exception?

**Comment by testt23** [comment]
this is the package that throws the exception. Above is an example of how I "debug" information with print_r.

**Comment by testt23** [comment]
Also, the "admin online" column is missing, which is in the demo
https://raw.githubusercontent.com/luyadev/luya-module-remoteadmin/master/remote-admin.png

**Comment by nadar** [comment]
Its an old screenshot indeed, this information is not displayed anymore.

**Comment by testt23** [comment]
I have a test this, but no change.
/RemoteController.php

```
<?php

namespace luya\admin\apis;

use Yii;
use luya\Boot;
use luya\Exception;
use luya\admin\models\UserOnline;
use luya\rest\Controller;

/**
 * Remove API, allows to collect system data with a valid $token.
 *
 * The remote api can only access with the oken but is not secured by a loggged in user.
 *
 * @author Basil Suter <basil@nadar.io>
 * @since 1.0.0
 */
class RemoteController extends Controller
{
    /**
     * Disabled the auth methods.
     *
     * @return boolean When false the authentication is disabled.
     */
    public function userAuthClass()
    {
        return false;
    }

    /**
     * Retrieve administration informations if the token is valid.
     *
     * @param string $token The sha1 encrypted access token.
     * @return array If invalid token.
     * @throws Exception
     */
    public function actionIndex($token)
    {
        if (empty(Yii::$app->remoteToken) || sha1(Yii::$app->remoteToken) !== $token) {
            throw new Exception('The provided remote token is wrong.');
        }
        
        UserOnline::clearList($this->module->userIdleTimeout);

        $packages = [];
        foreach (Yii::$app->getPackageInstaller()->getConfigs() as $name => $config) {
            $packages[$name] = [
                'package' => $config->package,
                'time' => Yii::$app->getPackageInstaller()->timestamp,
            ];
        }
        return [
            'yii_version' => Yii::getVersion(),
            'luya_version' => Boot::VERSION,
            'app_title' => Yii::$app->siteTitle,
            'app_debug' => (int) YII_DEBUG,
            'app_env' => YII_ENV,
            'app_transfer_exceptions' => (int) Yii::$app->errorHandler->transferException,
            'admin_online_count' => UserOnline::find()->count(),
            'app_elapsed_time' => Yii::getLogger()->getElapsedTime(),
            'packages' => $packages,
            'packages_update_timestamp' => Yii::$app->getPackageInstaller()->getTimestamp(),
        ];
    }
}

```

**Comment by nadar** [comment]
That should be sent correctly after next luya admin released.
