### ISSUE TITLE
Missing version for luya-module-admin

### ISSUE THREAD

**Issue by boehsermoe** [luyadev/luya-module-remoteadmin#7]
In the status page the version for `luya-module-admin` should be also listing under packages.

**Comment by nadar** [comment]
the version of the package should be listed when clicking on "packages" - as there are also applications without admin module. This what we are talking about, right?

**Comment by boehsermoe** [comment]
Exactly.

**Comment by nadar** [comment]
You mean because of 1.1.x dev?

**Comment by nadar** [comment]
![image](https://user-images.githubusercontent.com/3417221/45152160-8061b100-b1d0-11e8-878e-79a0e0834381.png)

**Comment by boehsermoe** [comment]
Hmm some of my projects have no admin module listed. I will take a closer look. Thank you.

**Comment by nadar** [comment]
If the package is missing, make sure to run the latest stable version (of the project). The package information for a given project is determined by the luya composer plugin which creates an installer.php file in the vendor. The informations from this file are the accessed trough remote call.
